{% set name = "cvxpygen" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cvxpygen-{{ version }}.tar.gz
  sha256: e830ce88006c57d7e292c9c601ea2a3ac5bfa58e4492e6937a95f67aae0c80ac

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - cmake >=3.5
    - cvxpy >=1.1.18
    - numpy >=1.15
    - osqp >=0.6.2
    - pybind11 >=2.8.0
    - python
    - scipy >=1.1.0

test:
  imports:
    - cvxpygen

about:
  home: https://github.com/cvxgrp/cvxpygen
  summary: Code generation with CVXPY
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
