{% set name = "cvxpygen" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cvxpygen-{{ version }}.tar.gz
  sha256: c5fb8951c80ab60f4482fdfbadd0641d67bed7d5eec2c2549eff8fa727627b27

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - cmake >=3.5
    - cvxpy >=1.1.18
    - numpy >=1.15
    - osqp >=0.6.2
    - pybind11 >=2.8.0
    - python
    - scipy >=1.1.0

test:
  imports:
    - cvxpygen

about:
  home: https://github.com/cvxgrp/cvxpygen
  summary: Code generation with CVXPY
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
